### ISSUE TITLE
Unit tests in pylast

### ISSUE THREAD

**Issue by IvanMalison** [pylast/pylast#110]
It says "Integration (not unit) tests for pylast.py" at the top of test_pylast.py. Where should unit tests be placed? is pylast_unit_tests.py okay. Why not have a test directory?

**Comment by hugovk** [comment]
Yeah, test_pylast.py aren't really unit tests because they're run against the real Last.fm network.

I'm open to suggestions, including renaming test_pylast.py if that make sense (test_integration_pylast.py?), and would like to follow common Python conventions where possible. test_ prefixes seem most common for filenames.

So a tests directory is a good idea. The current test_pylast.py is quite long. For new unit tests, it may make more sense to have more, but shorter, files. Perhaps test_user.py will test the User object, or something like that.

**Comment by IvanMalison** [comment]
How would you feel about switching to pytest instead of using unittest?

**Comment by hugovk** [comment]
I'd prefer to stick with unittest as the testing framework as I'm much more familiar with it. When it comes to a test runner, I'm more familiar with nosetests (for example with coverage) but I guess both should be able to run the unittest tests.
