### ISSUE TITLE
Start using https/SSL/TLS

### ISSUE THREAD

**Issue by simmel** [pylast/pylast#151]
Would be nice to have https/SSL/TLS support when communication with the Last.fm API.

With some mentoring insight into this codebase I'd be willing to contribute it.

**Comment by hugovk** [comment]
PRs welcome!

The `_Request` and `_BaseObject` classes are probably where you want to start off. `_Request` is the one that uses `HTTPConnection`.

The README has info on testing: https://github.com/pylast/pylast#testing

Because the Last.fm API is still partially broken after their recent update, I wouldn't worry about running the whole test suite. (Even when the API is working, the tests are a bit flaky as they're integration tests running against a third party whose state can change.) Rather write your own tests and test them in isolation like `py.test -k test_scrobble`. If you're able to have pure unit tests rather than or in addition to integration tests, so much the better.

But still, it's worth enabling [Travis CI](https://travis-ci.org/profile) (and [Coveralls](https://coveralls.io/repos/new)) for your repo.

**Comment by simmel** [comment]
Cool! I'll put it on my TODO

**Comment by vacuus** [comment]
I updated to use HTTPSConnection. It seems to be working just fine, but I'm not sure how to write a test. I tested by using Wireshark to confirm that I'm using TLS. Any suggestions?

Here's the branch I started: https://github.com/vacuus/pylast/tree/https .

**Comment by hugovk** [comment]
@vacuus Thanks! I don't think you need a Libre.fm key, just try calling it without. If all the calls are going through HTTPS, I guess the manual Wireshark check is fine and we don't need any specific tests, just that they all work. 

@simmel What do you think of this? https://github.com/pylast/pylast/compare/develop...vacuus:https 

Do you think it's fine to always use HTTPS, or should it be a configurable option?

**Comment by simmel** [comment]
On Tue, 2016-10-04 at 03:30:02 -0700, Hugo wrote:
> @vacuus Thanks! I don't think you need a Libre.fm key, just try calling it without. If all the calls are going through HTTPS, I guess the manual Wireshark check is fine and we don't need any specific tests, just that they all work. 
> 
> @simmel What do you think of this? https://github.com/pylast/pylast/compare/develop...vacuus:https 

Grr, I wanted to do the change! ; ) Damn you lack of time! *shakes fist
in air*

Looks like what I would have done except for one thing. Let's use the
[recommended Python SSL
settings](https://docs.python.org/2/library/ssl.html#best-defaults).

See https://github.com/pylast/pylast/compare/develop...simmel:https

> Do you think it's fine to always use HTTPS, or should it be a configurable option?

Always use HTTPS. Let's have less knobs and make it easier for the users
to get better privacy and be more secure (by default!).

**Comment by hugovk** [comment]
Would one of you like to create a pull request?

**Comment by simmel** [comment]
Done. Looks like some tests fail on Travis CI though? But it seems to be a lacking API key?

**Comment by hugovk** [comment]
Yes, it's because of https://github.com/pylast/pylast/issues/171, but don't worry about it for this, as long as some pass.
