### ISSUE TITLE
Artist.get_top_albums does not seem to work properly when limit =100

### ISSUE THREAD

**Issue by kochbj** [pylast/pylast#242]
Title says it all. It's possible I'm making a usage mistake, but when I specify "limit=100," it only gives me 50 items.

Thanks for all your hard work!

**Comment by hugovk** [comment]
pylast does send the parameter to Last.fm, and for some artists returns 100 albums per page, but for others only 50 per page. 

Compare these:

https://ws.audioscrobbler.com/2.0/?method=artist.gettopalbums&artist=Nirvana&limit=100&api_key=YOUR_API_KEY

https://ws.audioscrobbler.com/2.0/?method=artist.gettopalbums&artist=Ed%20Sheeran&limit=100&api_key=YOUR_API_KEY

With these:

https://ws.audioscrobbler.com/2.0/?method=artist.gettopalbums&artist=Cher&limit=100&api_key=YOUR_API_KEY

https://ws.audioscrobbler.com/2.0/?method=artist.gettopalbums&artist=The%20Fall&limit=100&api_key=YOUR_API_KEY

The fix is to page through subsequent `&page=2` etc. until we get `limit` items. Fixed by PR #243.

**Comment by hugovk** [comment]
This fix just been released in pylast 2.1.0.
