### ISSUE TITLE
user.getArtistTracks will be deprecated soon

### ISSUE THREAD

**Issue by ben-xo** [pylast/pylast#298]
Hi there,

We will be removing user.getArtistTracks from the public API soon. The new scrobble storage back-end doesn't support it, and the results returned by the method are slowly going out of date, as it's still powered by the legacy back-end.

However there is a new method user.getTrackScrobbles which is just like user.getArtistTracks, except also takes a "track" parameter. This covers the most frequent use cases for the getArtistTracks which have seen (such as "find my first scrobble of a specific song" or "work out how many times i played a particular song on a particular album")

The timeline for deprecation is sometime before May 2019.

**Comment by hugovk** [comment]
@ben-xo Hi, thanks for letting us know!

> We will be removing user.getArtistTracks from the public API soon. The new scrobble storage back-end doesn't support it, and the results returned by the method are slowly going out of date, as it's still powered by the legacy back-end.

I'll add a deprecation warning to `user.getArtistTracks` and add `user.getTrackScrobbles`. Is there any documentation for the new one yet?

For example, the old one is at https://www.last.fm/api/show/user.getArtistTracks, but https://www.last.fm/api/show/user.getTrackScrobbles is 404.

> However there is a new method user.getTrackScrobbles which is just like user.getArtistTracks, except also takes a "track" parameter. This covers the most frequent use cases for the getArtistTracks which have seen (such as "find my first scrobble of a specific song" or "work out how many times i played a particular song on a particular album")

I have a use case for the old `getArtistTracks` to list the last N (usually 20) tracks played by a user for a certain artist. It sounds like the new `getTrackScrobbles` cannot do that. Is that the case, and will there be something to replace it?

> The timeline for deprecation is sometime before May 2019.

Is that for when it will stop working, or for when it is officially discouraged? If the latter, do you have a timeline for when it will be switched off?

Thanks!

(PS `getArtistTracks` is returning 502 Bad Gateway or 504 Gateway Time-out right now.)

**Comment by ben-xo** [comment]
Hi there,

Sorry we haven't added the documentation yet - but it's basically the same as for user.getArtistTracks, except with a "track" parameter as well.

Unfortunately the only way to get information per-artist with the current scrobble-storage design is to either fetch information about all scrobbles (i.e user.getRecentTracks) then filter it, or to fetch information about an artist (user.getTopTracks filtered by artist) and then poll the histories for each track. So, that's the workaround for your use case. We don't currently plan to offer that as a single method.

**Comment by hugovk** [comment]
I released pylast 3.1.0 this morning which warns about the deprecation and adds the new method.

Cheers!

**Comment by kenmacf** [comment]
I've got a similar use case, like the one @hugovk mentioned, retrieve the last N tracks by a particular artist; in my case, I also perform analysis on the track scrobble time and frequency.  user.getArtistTracks was also convenient because I could collaborate track names that included information about remaster, about featured artist, misspellings, etc. that for my purposes were identical.

The next-best options for my (re-)coding exercise appear to be:

1. Is there an API call behind the library page that shows number of tracks listened to by artist, for example, https://www.last.fm/user/rj/library/music/Metallica/+tracks.  I didn't see an option in the API documentation to get data in this format.  It would give the best information on which tracks to pass along to user.getTrackScrobbles.  (If there's no API call backing this page, then it's tempting to write a web scraper, but I promise I won't.)
2. Run the following steps:
- Run artist.getInfo with the username parameter to get total listens by artist for the user
- Run artist.getTopTracks
- For each top track, run user.getTrackScrobbles until number of tracks retrieved matches the value from artist.getInfo
3. Run artist.getInfo the same as in #2, but then run user.getTopTracks repeatedly, searching for the artist during each call until I've reached total number of artist tracks.  

Adding some client-side caching may improve performance and reduce load on the API server.  However, it still seems like a bit of an odd tradeoff--by no longer supporting artist.getTopTracks, now I'm adding a performance drag to the API service by having to make potentially hundreds of API calls to get all the information I needed, when previously I could usually get what I needed with very few API calls.

**Comment by hugovk** [comment]
@ben-xo `user.getArtistTracks` is now returning an empty list. 

```json
{"artisttracks": {"track": [],"@attr": {"user": "bbc6music","artist": "metallica","page": "1","perPage": "50","totalPages": "0","total": "0"}}}
```

Has it officially been removed from the API? If so, perhaps returning an error code such as "27 : Deprecated - This type of request is no longer supported" would be better?

(See also https://getsatisfaction.com/lastfm/topics/user-getartisttracks-returns-empty-list)

Thanks!

**Comment by ben-xo** [comment]
@hugovk The deprecation message code was queued up for release at our end, and has now been released.

**Comment by hugovk** [comment]
Confirmed, thanks!

```json
{
"error": 27,
"message": "Deprecated - This type of request is no longer supported"
}
```

https://ws.audioscrobbler.com/2.0/?method=user.getartisttracks&user=rj&artist=metallica&api_key=YOUR_API_KEY&format=json

**Comment by ben-xo** [comment]
@kenmacf I understand the concern. I do admit that it seems, at first, like an odd trade-off from the client perspective. But the process you outlined - getTopTracks, then for each track, getTrackScrobbles - is the process we would have to run, internally, to generate the result to keep this API method in place. 

It is likely that the call would tie up a lot of server resources, and the method would take a long time and be nearly as slow to run. Additionally, I expect that it would time-out for users with large libraries, offering you no chance to resume a partially completed request, and forcing you to start the request again from scratch.

Perhaps, for the use cases you have in mind, it would make sense to add an emulation for this method into pylast?

**Comment by kenmacf** [comment]
> @kenmacf I understand the concern. I do admit that it seems, at first, like an odd trade-off from the client perspective. But the process you outlined - getTopTracks, then for each track, getTrackScrobbles - is the process we would have to run, internally, to generate the result to keep this API method in place.
> 
> The external API calls themselves, and the interface onto the backend services, are relatively cheap for us - the number of uses of this API method is so small that it's not a performance concern for us even to multiply it by 100x.

Thanks for the feedback.  One of my main concerns is that my API calls still remain within the realm of good citizenship even though the number may significantly increase.

(Although I'm still curious if there's a way to do option 1, especially once the updated API documentation is published, before I go down the path of option 2.)

> Perhaps, for the use cases you have in mind, it would make sense to add an emulation for this method into pylast?

I'll be glad to share some working code once I get around to producing it.  I'd also be glad to coordinate testing of larger datasets for performance analysis if desired.

**Comment by kenmacf** [comment]
quick update--I've (mostly) achieved a workaround through calling user.getRecentTracks and re-indexing in DynamoDB on artist+scrobble time.  I can update my data copy with at most a few last.fm API calls each day, so number of resource utilization there is fairly low.  Uploading the data that I wanted to keep in DynamoDB cost me less than US$1 for my full history, and cost of read calls is negligible.

Still needs a few tweaks, but appears to be a usable solution.
