### ISSUE TITLE
User.get_recent_tracks returns limit-1 if user is currently scrobbling

### ISSUE THREAD

**Issue by pavelgar** [pylast/pylast#309]
### What did you do?
`User.get_recent_tracks(limit=10)`

### What did you expect to happen?
`User.get_recent_tracks(limit=10)` to return a list of length 10.

### What actually happened?
`User.get_recent_tracks(limit=10)` returned a list of length 9 because the user was currently scrobbling.

### What versions of OS, Python and pylast are you using?
macOS Mojave 10.14.4
Python 3.7
pylast 3.1.0

**Comment by hugovk** [comment]
Thanks for the report, that'll be because the now playing track is removed, if it exists:

* https://github.com/pylast/pylast/blob/fc51315f48524af15600f7ee4a86d4670f136c15/src/pylast/__init__.py#L2395-L2396

The workaround is to request `N+1` tracks and slice `tracks[:N]`:

```python
tracks = User.get_recent_tracks(limit=10+1)
tracks = tracks[:10]
```

The fix is to do the same sort of thing inside `get_recent_tracks`.

**Comment by hugovk** [comment]
Please can you try PR https://github.com/pylast/pylast/pull/310?

**Comment by pavelgar** [comment]
PR #310 works for me. Thanks!
Setting limit to 0 works as expected :)
