### ISSUE TITLE
artist.get_cover_image always returns default star image

### ISSUE THREAD

**Issue by manatlan** [pylast/pylast#317]
Hi, it seems that there is a lastfm trouble here ... no ?
I do:
```python
import pylast

API_KEY = "ca19f8d10f5db8c" # fake
API_SECRET = "dd427cf6417aca2c7e"

username = "user"
password_hash = pylast.md5("passwd")

network = pylast.LastFMNetwork(api_key=API_KEY, api_secret=API_SECRET,
                               username=username, password_hash=password_hash)

artist = pylast.Artist("dEUS", network)
print(artist.get_cover_image())
```
it always return the blank cover "https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png" ...
for all wanted artist ;-(

**Comment by hugovk** [comment]
Unfortunately this is an intentional change on Last.fm's side:

> We’ve made changes to our API in order to limit abuse and improve the service for everyone, in line with our API Terms of Use. 
>
> While we allow API users to have access to a lot of data through the API, it has always been against our API Terms of Use for third parties to use audio, audiovisual, images or artwork. In some instances, some data may have been indirectly accessible through a small number of API calls, and so as part of the recent API clean-up, we have corrected that anomaly.
>
> If your application is affected, please refer to our API Terms of Use to ensure your compliance.

https://getsatisfaction.com/lastfm/topics/api-announcement-dac8oefw5vrxq
 
An alternative API for artist images is from MusicBrainz. If you're dealing with Last.fm data, you may already have the MBID for the artist, which you query like this:

* https://stackoverflow.com/a/28467856/724176

Here's a JavaScript example:

https://github.com/hugovk/now-playing-radiator/commit/e6de980db9da6846edc5aa2d2f7057b8f3b21bc8

**Comment by spiritualized** [comment]
This library will help you work around the issue: https://github.com/spiritualized/lastfmcache
